language: node_js
node_js:
  - 12
before_install:
  - npm i -g npm
install:
  - npm ci
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: N70HF9JpFsuqDPhlxiomlmj9yriZSmaEwfcGxKwL6VOAn5t4+qeXsCOQd6W0jnn/tOpd91hgDdX5cOCNNdqKWHjHXPIsgOlRDmshAFJ+6LCUa4o1hV1ay9rH8c8KwnShs3GKlNgZReoIEoClw8Z/chKcYunJeLN74Wd/csBc2DG/gpzjJR8zs1smp5uNO70G0VRmId63pe+VmQ/OwkLDlgAw9cp7AIGpDlSIfaJNjGuQCOcBoe0uRyePcsbnE3MhCw1jGglSB8MzR1gwFs0Q+ymjNyqhCYKCUX6cq71dScftbye+lz3kvYqRJulWZNqUPkkyyaTx42Aasjzhokl2qoAjKSd1f/KHyXp7dXdEY0+9Z9ugXiPIfA+saZhfWAeGkv6W/q9WRVNiJpDeGKNJtbn+4421lQx2R0yrxzhp8AUXTnIjPNG4PSv+bhyHzqhBRwU6OSW4QnPUIu2YROFdPIovHc7dxYnRw4iJRMAVFSwPS7lIRCrDGZd5+yXdWDbkUAlKXqLoIYwHitf7shThFzjRB3E4grFoi9yO/KlFMbmacDwcvkRU5AgVSBvO5h7tOLSGQzeEF7/l4zNHUMCvrKVxPGvaBwiiBMvSfrw7fIZ2Un9ypsacdH1Yxi2ND3MdxJgdX9M07mQBO75Y982MYzWmuoEGjmDvm8/4eXSeV0Q=
  app: compassed-api
  on:
    repo: Holajuwon/compass-api
    branch: develop
services:
  - postgresql
before_script:
  - psql -c 'create database my_db;' -U postgres
  - psql "dbname=my_db" -a -f init.sql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - DB_USER=postgres
    - DB_HOST=localhost
    - DB_DATABASE=my_db
    - DB_PORT=5432
    - DB_PASSWORD=
